// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HP.proto

package com.hawk.game.protocol;

public final class HP {
  private HP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code sys}
   *
   * <pre>
   * 系统协议ID列表(&lt;100)
   * </pre>
   */
  public enum sys
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA_WRAPPER = 1;</code>
     *
     * <pre>
     * 数据封装
     * </pre>
     */
    DATA_WRAPPER(0, 1),
    /**
     * <code>KEY_EXCHANGE = 2;</code>
     *
     * <pre>
     * 秘钥交换
     * </pre>
     */
    KEY_EXCHANGE(1, 2),
    /**
     * <code>HEART_BEAT = 3;</code>
     *
     * <pre>
     * 心跳通知
     * </pre>
     */
    HEART_BEAT(2, 3),
    /**
     * <code>ERROR_CODE = 4;</code>
     *
     * <pre>
     * 错误码提示
     * </pre>
     */
    ERROR_CODE(3, 4),
    ;

    /**
     * <code>DATA_WRAPPER = 1;</code>
     *
     * <pre>
     * 数据封装
     * </pre>
     */
    public static final int DATA_WRAPPER_VALUE = 1;
    /**
     * <code>KEY_EXCHANGE = 2;</code>
     *
     * <pre>
     * 秘钥交换
     * </pre>
     */
    public static final int KEY_EXCHANGE_VALUE = 2;
    /**
     * <code>HEART_BEAT = 3;</code>
     *
     * <pre>
     * 心跳通知
     * </pre>
     */
    public static final int HEART_BEAT_VALUE = 3;
    /**
     * <code>ERROR_CODE = 4;</code>
     *
     * <pre>
     * 错误码提示
     * </pre>
     */
    public static final int ERROR_CODE_VALUE = 4;


    public final int getNumber() { return value; }

    public static sys valueOf(int value) {
      switch (value) {
        case 1: return DATA_WRAPPER;
        case 2: return KEY_EXCHANGE;
        case 3: return HEART_BEAT;
        case 4: return ERROR_CODE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<sys>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<sys>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<sys>() {
            public sys findValueByNumber(int number) {
              return sys.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.HP.getDescriptor().getEnumTypes().get(0);
    }

    private static final sys[] VALUES = values();

    public static sys valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private sys(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sys)
  }

  /**
   * Protobuf enum {@code code}
   *
   * <pre>
   * 游戏协议ID列表(&gt;=100)
   * </pre>
   */
  public enum code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_C = 1000;</code>
     *
     * <pre>
     * 登陆
     * </pre>
     */
    LOGIN_C(0, 1000),
    /**
     * <code>LOGIN_S = 1001;</code>
     */
    LOGIN_S(1, 1001),
    ;

    /**
     * <code>LOGIN_C = 1000;</code>
     *
     * <pre>
     * 登陆
     * </pre>
     */
    public static final int LOGIN_C_VALUE = 1000;
    /**
     * <code>LOGIN_S = 1001;</code>
     */
    public static final int LOGIN_S_VALUE = 1001;


    public final int getNumber() { return value; }

    public static code valueOf(int value) {
      switch (value) {
        case 1000: return LOGIN_C;
        case 1001: return LOGIN_S;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<code>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<code>() {
            public code findValueByNumber(int number) {
              return code.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.HP.getDescriptor().getEnumTypes().get(1);
    }

    private static final code[] VALUES = values();

    public static code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private code(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:code)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010HP.proto*I\n\003sys\022\020\n\014DATA_WRAPPER\020\001\022\020\n\014K" +
      "EY_EXCHANGE\020\002\022\016\n\nHEART_BEAT\020\003\022\016\n\nERROR_C" +
      "ODE\020\004*\"\n\004code\022\014\n\007LOGIN_C\020\350\007\022\014\n\007LOGIN_S\020\351" +
      "\007B\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
