// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package com.hawk.game.protocol;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HPPlayerKickoutOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 reason = 1;
    /**
     * <code>required int32 reason = 1;</code>
     */
    boolean hasReason();
    /**
     * <code>required int32 reason = 1;</code>
     */
    int getReason();
  }
  /**
   * Protobuf type {@code HPPlayerKickout}
   */
  public static final class HPPlayerKickout extends
      com.google.protobuf.GeneratedMessage
      implements HPPlayerKickoutOrBuilder {
    // Use HPPlayerKickout.newBuilder() to construct.
    private HPPlayerKickout(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPPlayerKickout(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPPlayerKickout defaultInstance;
    public static HPPlayerKickout getDefaultInstance() {
      return defaultInstance;
    }

    public HPPlayerKickout getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPPlayerKickout(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reason_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Player.internal_static_HPPlayerKickout_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Player.internal_static_HPPlayerKickout_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Player.HPPlayerKickout.class, com.hawk.game.protocol.Player.HPPlayerKickout.Builder.class);
    }

    public static com.google.protobuf.Parser<HPPlayerKickout> PARSER =
        new com.google.protobuf.AbstractParser<HPPlayerKickout>() {
      public HPPlayerKickout parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPPlayerKickout(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPPlayerKickout> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 reason = 1;
    public static final int REASON_FIELD_NUMBER = 1;
    private int reason_;
    /**
     * <code>required int32 reason = 1;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 reason = 1;</code>
     */
    public int getReason() {
      return reason_;
    }

    private void initFields() {
      reason_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReason()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Player.HPPlayerKickout parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Player.HPPlayerKickout prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPPlayerKickout}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Player.HPPlayerKickoutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Player.internal_static_HPPlayerKickout_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Player.internal_static_HPPlayerKickout_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Player.HPPlayerKickout.class, com.hawk.game.protocol.Player.HPPlayerKickout.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Player.HPPlayerKickout.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reason_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Player.internal_static_HPPlayerKickout_descriptor;
      }

      public com.hawk.game.protocol.Player.HPPlayerKickout getDefaultInstanceForType() {
        return com.hawk.game.protocol.Player.HPPlayerKickout.getDefaultInstance();
      }

      public com.hawk.game.protocol.Player.HPPlayerKickout build() {
        com.hawk.game.protocol.Player.HPPlayerKickout result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Player.HPPlayerKickout buildPartial() {
        com.hawk.game.protocol.Player.HPPlayerKickout result = new com.hawk.game.protocol.Player.HPPlayerKickout(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reason_ = reason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Player.HPPlayerKickout) {
          return mergeFrom((com.hawk.game.protocol.Player.HPPlayerKickout)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Player.HPPlayerKickout other) {
        if (other == com.hawk.game.protocol.Player.HPPlayerKickout.getDefaultInstance()) return this;
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReason()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Player.HPPlayerKickout parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Player.HPPlayerKickout) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 reason = 1;
      private int reason_ ;
      /**
       * <code>required int32 reason = 1;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 reason = 1;</code>
       */
      public int getReason() {
        return reason_;
      }
      /**
       * <code>required int32 reason = 1;</code>
       */
      public Builder setReason(int value) {
        bitField0_ |= 0x00000001;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 reason = 1;</code>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPPlayerKickout)
    }

    static {
      defaultInstance = new HPPlayerKickout(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPPlayerKickout)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPPlayerKickout_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPPlayerKickout_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\"!\n\017HPPlayerKickout\022\016\n\006rea" +
      "son\030\001 \002(\005B\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPPlayerKickout_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPPlayerKickout_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPPlayerKickout_descriptor,
              new java.lang.String[] { "Reason", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
