// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

package com.hawk.game.protocol;

public final class Status {
  private Status() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code error}
   */
  public enum error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONFIG_ERROR = 1;</code>
     *
     * <pre>
     * 配置文件错误
     * </pre>
     */
    CONFIG_ERROR(0, 1),
    /**
     * <code>ONLINE_MAX_LIMIT = 2;</code>
     *
     * <pre>
     * 在线人数达到上限
     * </pre>
     */
    ONLINE_MAX_LIMIT(1, 2),
    /**
     * <code>REGISTER_MAX_LIMIT = 3;</code>
     *
     * <pre>
     * 注册人数达到上限
     * </pre>
     */
    REGISTER_MAX_LIMIT(2, 3),
    /**
     * <code>SERVER_GRAY_STATE = 4;</code>
     *
     * <pre>
     * 服务器灰度状态中
     * </pre>
     */
    SERVER_GRAY_STATE(3, 4),
    ;

    /**
     * <code>CONFIG_ERROR = 1;</code>
     *
     * <pre>
     * 配置文件错误
     * </pre>
     */
    public static final int CONFIG_ERROR_VALUE = 1;
    /**
     * <code>ONLINE_MAX_LIMIT = 2;</code>
     *
     * <pre>
     * 在线人数达到上限
     * </pre>
     */
    public static final int ONLINE_MAX_LIMIT_VALUE = 2;
    /**
     * <code>REGISTER_MAX_LIMIT = 3;</code>
     *
     * <pre>
     * 注册人数达到上限
     * </pre>
     */
    public static final int REGISTER_MAX_LIMIT_VALUE = 3;
    /**
     * <code>SERVER_GRAY_STATE = 4;</code>
     *
     * <pre>
     * 服务器灰度状态中
     * </pre>
     */
    public static final int SERVER_GRAY_STATE_VALUE = 4;


    public final int getNumber() { return value; }

    public static error valueOf(int value) {
      switch (value) {
        case 1: return CONFIG_ERROR;
        case 2: return ONLINE_MAX_LIMIT;
        case 3: return REGISTER_MAX_LIMIT;
        case 4: return SERVER_GRAY_STATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<error>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<error>() {
            public error findValueByNumber(int number) {
              return error.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.Status.getDescriptor().getEnumTypes().get(0);
    }

    private static final error[] VALUES = values();

    public static error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private error(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Status.proto*^\n\005error\022\020\n\014CONFIG_ERROR\020" +
      "\001\022\024\n\020ONLINE_MAX_LIMIT\020\002\022\026\n\022REGISTER_MAX_" +
      "LIMIT\020\003\022\025\n\021SERVER_GRAY_STATE\020\004B\030\n\026com.ha" +
      "wk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
